---
title: "[eb1] Measurement - Quality Control"
author: "Egor Ananyev"
date: "2019-01-04"
output:
    html_document:
        toc: true
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
body, td{
  font-family: Cambria;
}
code.r{
  font-family: Inconsolata;
}
</style>

# Data input and parsing
```{r set-options, message=F}
options(width=100)
computer = 'acer'  # 'shocky', 'station3', 'acer' are all possible options
debug = F
short_rt_cutoff = 0.2
long_rt_cutoff = 1
library(plyr)
library(ggplot2)
if(computer == 'shocky'){ dropbox_dir='/Users/Egor/Dropbox/' }
if(computer == 'acer'){ dropbox_dir='/Users/egora/Dropbox/' }
source(paste(dropbox_dir, 'Projects/eb/eb/an/funs/BF_t.R', sep='/'))
source(paste(dropbox_dir, 'Projects/eb/eb/an/funs/BF_U.R', sep='/'))
all_data_dir = paste0(dropbox_dir, 'Projects/eb/data/eb1/')
conds = c('cond-a', 'cond-c', 'cond-v')
cue_conds = c('cp', 'cu')  # cue predictive and unpredictive
ds = data.frame()
et = data.frame()
excl = data.frame()
# cur_cue_cond = cue_conds[1]
for(cur_cue_cond in cue_conds){
  cur_cue_bin = as.numeric(cur_cue_cond == 'cp')  # binary variable for whether the cue is pred've
  data_dir = paste0(all_data_dir, cur_cue_cond, '/')
  subjs = dir(data_dir, pattern='subj-')
  # cur_subj = subjs[1]  # temp
  for(cur_subj in subjs){
    cur_subj_dir = paste0(data_dir, cur_subj)
    # cur_cond = conds[1]  # temp
    for(cur_cond in conds){
      cur_cond_dir = paste(cur_subj_dir, cur_cond, sep='/')
      sesss = dir(cur_cond_dir, pattern='sess-')
      # cur_sess = sesss[1]  # temp
      for(cur_sess in sesss){
        cur_sess_dir = paste(cur_cond_dir, cur_sess, sep='/')
        print(cur_sess_dir)
        cur_ds = read.csv(paste(cur_sess_dir, 'beh_out.csv', sep='/'))
        # Making sure 'cue_pred' column exists; if not, writing it in:
        if(!'cue_pred' %in% colnames(cur_ds)){
          cur_ds$cue_pred = cur_cue_bin
        } else {
          if(unique(cur_ds$cue_pred) != cur_cue_bin){
            print('ERROR! Cue predictiveness condition does not match the data!')
          }
        }
        # Reading the eye-tracking data:
        cur_et = read.csv(paste(cur_sess_dir, 'eye_tracking.csv', sep='/'))
        cur_et = cbind(data.frame(subj=cur_subj, cond=cur_cond, sess=cur_sess),
                       cur_et)
        # For eye-tracking data, making sure that the extra columns from AB cond are present:
        if(!cur_cond == 'a'){
          cur_et = cbind(data.frame(shutter_sample_beg = NA, shutter_time_beg = NA,
                                    shutter_sample_end = NA, shutter_time_end = NA,
                                    cue_resp_sample = NA, cue_resp_time = NA),
                         cur_et)
          # cur_et$shutter_sample_beg = NA
          # cur_et$shutter_time_beg = NA
          # cur_et$shutter_sample_end = NA
          # cur_et$shutter_time_end = NA
          # cur_et$cue_resp_sample = NA
          # cur_et$cue_resp_time = NA
        }
        # print(colnames(cur_ds))  # debug
        # ds = cur_ds  # temp
        ds = rbind(ds, cur_ds)
        print(colnames(et))
        print(colnames(cur_et))
        et = rbind(et, cur_et)
        excl_file = paste(cur_sess_dir, 'exclude_trials.csv', sep='/')
        if(file.exists(excl_file)){
          excl_file_ds = read.csv(excl_file)
          if(nrow(excl_file_ds) > 0){
            cur_excl = cbind(data.frame(subj=as.numeric(substr(cur_subj, 6, 7)), 
                                        cue_pred=cur_cue_bin,
                                        cond=substr(cur_cond, 6, 6),
                                        sess=as.numeric(substr(cur_sess, 6, 6))), excl_file_ds)
            excl = rbind(excl, cur_excl)
          }
        }
      }
    }
  }
}
colnames(ds)[5] = 'trial'  # renaming the 'trial_id' column to 'trial'
head(ds)
# print(excl)
```

# Cleaning the data
```{r}
# Excluding trials with RTs that are too short (below 200 ms)
excl_short = ds[ds$rt<short_rt_cutoff, c('subj', 'cue_pred', 'cond', 'sess', 'trial')]
if(nrow(excl_short) > 0){  # if there are any trials to exclude based on the short RTs
  colnames(excl_short)[5] = 'trial'  # renaming the 'trial_id' column to 'trial'
  excl_short$excl_reason = 'short RT'  # including exclusion reason
  ## Adding the short trials to the common exclusion list:
  excl = rbind(excl, excl_short)
  rownames(excl) <- NULL
}
excl_long = ds[ds$rt>long_rt_cutoff, c('subj', 'cue_pred', 'cond', 'sess', 'trial')]
if(nrow(excl_long) > 0){
  colnames(excl_long)[5] = 'trial'  # renaming the 'trial_id' column to 'trial'
  excl_long$excl_reason = 'long RT'  # including exclusion reason
  excl = rbind(excl, excl_long)
  rownames(excl) <- NULL
}
excl_false = ds[ds$corr_resp==0, c('subj', 'cue_pred', 'cond', 'sess', 'trial')]
if(nrow(excl_false) > 0){
  colnames(excl_false)[5] = 'trial'  # renaming the 'trial_id' column to 'trial'
  excl_false$excl_reason = 'incorrect response'  # including exclusion reason
  excl = rbind(excl, excl_false)
  rownames(excl) <- NULL
}
# Displaying number of trials to be excluded, based on condition and session
library(dplyr)
ddply(excl, .(subj, cue_pred, cond, excl_reason), summarise, num_excl = length(trial))
# Excluding trials based on the quality control & the RT exclusion criteria:
ds = anti_join(ds, excl, by=c('subj', 'cue_pred', 'cond', 'sess', 'trial'))
```

# Merging eye tracking and behavioral data
```{r}
# Excluding dropped trials from the eye tracking data set before merging:

# Merging:
dsa = merge(ds, )
```

# Summary stats
```{r}
ddply(ds, .(subj, cue_pred, cond, cue_valid), summarise, mean_RT = mean(rt))
```

# Better condition names
```{r}
ds$Cond = 'NoBlink'
ds$Cond[ds$cond=='a'] = 'Artificial'
ds$Cond[ds$cond=='v'] = 'Prompted'
ds$CondFull = 'No Blink'
ds$CondFull[ds$cond=='a'] = 'Artificial Blink'
ds$CondFull[ds$cond=='v'] = 'Prompted Blink'
ds$CuePred = 'Predictive'
ds$CuePred[ds$cue_pred==0] = 'Unpredictive'
ds$CueValid = 'Valid'
ds$CueValid[ds$cue_valid==0] = 'Invalid'
```

# Visualization
## Cueing
```{r, fig.width=3, fig.height=2.5}
# for(cur_cue in unique(ds$cue_pred)){
#   for(cur_subj in unique(ds$subj)){
#     for(cur_cond in c('a','c','v')){
#       cur_ds = ds[ds$cond==cur_cond & ds$subj==cur_subj & ds$cue_pred==cur_cue,]
#       cur_cond_name = unique(cur_ds$CondFull)
#       p = ggplot(data=cur_ds, aes(x=factor(cue_valid), y=rt))
#       p = p + theme_bw() + ylim(short_rt_cutoff, .9)
#       p = p + geom_dotplot(binaxis='y', stackdir='center', dotsize=1, binwidth=.02)
#       p = p + ggtitle(paste('cond', cur_cond_name))
#       suppressWarnings(plot(p))
#     }
#   }
# }
```

```{r, fig.width=3, fig.height=2.5}
for(cur_cue in unique(ds$cue_pred)){
  print('-----------------------------------------------------------------------------------')
  print(paste('cue predictive?', as.character(cur_cue)))
  for(cur_subj in unique(ds$subj)){
    for(cur_cond in c('a','c','v')){
      cur_ds = ds[ds$cond==cur_cond & ds$subj==cur_subj & ds$cue_pred==cur_cue,]
      cur_plot_name = paste0(unique(cur_ds$CondFull), ': ', 'Participant ',
                             as.character(cur_subj))
      p = ggplot(data=cur_ds, aes(x=rt, colour=factor(cue_valid))) + geom_density() +
        theme(legend.position = 'bottom') + ggtitle(cur_plot_name)
      plot(p)
    }
  }
}
```

## Cueing group plots

### Density plots
```{r, fig.width=6, fig.height=2.5}
plot_dens = function(cue_pred_val, plot_title){
  ggplot(data=ds[ds$cue_pred==cue_pred_val,], aes(x=rt, colour=CueValid)) + 
    geom_density() + facet_grid(.~CondFull) + theme(legend.position = 'bottom') + 
    ggtitle(plot_title) + guides(colour=guide_legend(title='Cue Validity'))
}
plot(plot_dens(0, 'Unpredictive Cue'))
plot(plot_dens(1, 'Predictive Cue'))
```

### Box plots
```{r, fig.width=5, fig.height=3}
sumss = ddply(ds, .(subj, cue_pred, CueValid, CondFull), summarise, RT=median(rt))
plot_box = function(cue_pred_val, plot_title){
  ggplot(data=sumss[sumss$cue_pred==cue_pred_val,], aes(x=CueValid, y=RT, colour=CueValid)) + 
    geom_boxplot() + facet_grid(.~CondFull) + xlab('Cue Validity') + ylim(.25,.5) +
    theme(legend.position='none') + ggtitle(plot_title)
}
plot(plot_box(0, 'Unpredictive Cue'))
plot(plot_box(1, 'Predictive Cue'))
```

# Analyses

## Linear models
```{r}
# Reordering levels of Condition variable, such that No Blink condition is the reference:
ds$Cond <- factor(ds$Cond, c('NoBlink','Artificial','Prompted')) #this works for lm
summary(lm(rt~Cond*cue_valid*cue_pred, data=ds))  # switch to lme4 for mixed models
# 1 / generalTestBF(rt ~ cond*cue_valid, data=ds, whichModels='top')
library(lme4)
summary(lmer(rt~Cond*cue_valid*cue_pred + (1|subj), data=ds))
```

## Bayes Factor
```{r}
# library(BayesFactor)
# bf_ss = ds
# bf_ss$subj <- factor(bf_ss$subj)
# bf_ss$AB = 0
# bf_ss$AB[bf_ss$cond=='a'] = 1
# bf_ss$PB = 0
# bf_ss$PB[bf_ss$cond=='v'] = 1
# bf_ss$NB = 0
# bf_ss$NB[bf_ss$cond=='c'] = 1
# mRes = 1/generalTestBF(rt ~ cue_valid * cue_pred + subj, 
#                   data=bf_ss[bf_ss$NB==1,], whichRandom='subj', neverExclude='subj', 
#                   whichModels='top')
# print(mRes)
# mRes = 1/generalTestBF(rt ~ AB * cue_valid * cue_pred + subj, 
#                   data=bf_ss[bf_ss$PB==0,], whichRandom='subj', neverExclude='subj', 
#                   whichModels='top')
# print(mRes)
# mRes = 1/generalTestBF(rt ~ PB * cue_valid * cue_pred + subj, 
#                   data=bf_ss[bf_ss$AB==0,], whichRandom='subj', neverExclude='subj', 
#                   whichModels='top')
# print(mRes)
```

# Blink-related analysis

## Plots


## Analysis