---
title: "[eb23] Comparing Expts 2 & 3"
author: "Egor Ananyev"
date: "2020-07-10"
output:
    html_document:
        toc: true
editor_options: 
  chunk_output_type: inline
---

<style type="text/css">
body, td{
  font-family: Cambria;
}
code.r{
  font-family: Inconsolata;
}
</style>

# Data and function input

```{r set-options, message=F}
# options(width=100)
library(plyr)
library(dplyr)
library(ggplot2)
library(lme4)
computer = 'acer'  # 'shocky', 'station3', 'acer' are all possible options
if(computer == 'shocky' || computer == 'toshi'){ cloud_dir='/Users/Egor/Dropbox/' }
if(computer == 'acer'){ cloud_dir='C:/Users/egora/Prog' }
source(paste(cloud_dir, 'eb/an/funs_an/BF_t.R', sep='/'))
source(paste(cloud_dir, 'eb/an/funs_an/BF_U.R', sep='/'))
## Data input
ds1 = read.csv(paste(cloud_dir, 'eb/an/consolidated/ds1.csv', sep='/'))
dsa1 = read.csv(paste(cloud_dir, 'eb/an/consolidated/dsa1.csv', sep='/'))
ds2 = read.csv(paste(cloud_dir, 'eb/an/consolidated/ds2.csv', sep='/'))
dsa2 = read.csv(paste(cloud_dir, 'eb/an/consolidated/dsa2.csv', sep='/'))
ds3 = read.csv(paste(cloud_dir, 'eb/an/consolidated/ds3.csv', sep='/'))
dsa3 = read.csv(paste(cloud_dir, 'eb/an/consolidated/dsa3.csv', sep='/'))
```

# Transformations

```{r}
summary(ds1$ctoa)
ds1$targ_bin[ds1$ctoa < 700] = 'Early Target'
ds1$targ_bin[ds1$ctoa > 835] = 'Middle Target'
print(ddply(ds1, .(targ_bin), summarise, num=length(targ_bin)))
```

```{r}
ds3$targ_bin[ds3$targ_soa==0.6] = 'Early Target'
ds3$targ_bin[ds3$targ_soa==0.9] = 'Middle Target'
ds3$targ_bin[ds3$targ_soa==1.2] = 'Late Target'
ds3 = ds3[!is.na(ds3$targ_bin),]
print(ddply(ds3, .(targ_bin), summarise, num=length(targ_bin)))
```


```{r}
## Only including the predictive cueing condition from Expt 2:
ds2 = ds2[ds2$cue_pred==1,]
## Binning CTOAs from the Expt 2 into early, mid, and late.
## This roughly corresponds to Expt 3's 600, 900, and 1200 ms CTOA levels.
ds2$targ_bin = NA
ds2$targ_bin[ds2$ctoa < 800] = 'Early Target'
ds2$targ_bin[ds2$ctoa > 850 & ds2$ctoa < 950] = 'Middle Target'
ds2$targ_bin[ds2$ctoa > 1150 & ds2$ctoa < 1250] = 'Late Target'
# Only including binned target SOAs (without NA's that fall outside the binning ranges):
ds2 = ds2[!is.na(ds2$targ_bin),]
ds2$targ_bin = as.factor(ds2$targ_bin)
print(levels(ds2$targ_bin))
print(ddply(ds2, .(targ_bin), summarise, num=length(targ_bin)))
```

```{r}
## Combining the two datasets:
common_cols = c('exp_name', 'Cond', 'cue_valid', 'subj', 'RT', 'CueValid', 'targ_bin', 'corr_resp')
ds = rbind(ds1[,common_cols], ds2[,common_cols], ds3[,common_cols])
## A better-named experiment column:
ds$expt = ''
ds$expt[ds$exp_name=='eb1'] = 'Expt1'
ds$expt[ds$exp_name=='eb2'] = 'Expt2'
ds$expt[ds$exp_name=='eb3'] = 'Expt3'
## Sanity check
## Reordering the levels
ds$Cond = factor(ds$Cond, c('Prompted','NoBlink','Artificial')) #this works for lm
print(head(ds))
```

# Linear models

## Model with CTOA

```{r}
summary(lmer(RT~expt*Cond*cue_valid*targ_bin + (1|subj), data=ds))
```

Comments here.

## Model without CTOA

```{r}
summary(lmer(RT~expt*Cond*cue_valid + (1|subj), data=ds))
```


# Visualization

## Valid / Invalid separately

```{r, fig.width=7.5, fig.height=5.5}
sumss = ddply(ds, .(subj, expt, Cond, CueValid, targ_bin), summarise, RT=median(RT))
p = ggplot(data=sumss, aes(x=targ_bin, y=RT, fill=CueValid)) + 
    geom_boxplot() + facet_grid(Cond~expt) + xlab('Target CTOA') + 
    ylab('RT (ms)') + theme_bw() + 
    # geom_dotplot(binaxis='y', stackdir='center', dotsize=2, binwidth=3, ) + 
    theme(panel.grid.minor=element_blank(), 
          plot.title = element_text(hjust = 0.5)) + ggtitle('Experiments 2 & 3 Comparison')
plot(p)
pdf('eb_box_expts2-3.pdf', width=7.5, height=5.5)
plot(p)
dev.off()
```


## Computing cueing advantage
```{r}
library(R.utils)
sourceDirectory(paste(cloud_dir, 'eb/an/funs_an', sep='/'))
out = T
ss_corr = ds[ds$corr_resp==1, ]
ctoa_valid = ddply(ss_corr[ss_corr$CueValid=='Valid',], .(expt, targ_bin, Cond, subj), summarise,
                   RT=median(RT))
# plot_box_ctoa(ctoa_valid, 'RT Valid (ms)', 'RT on Valid Trials', out, 'targ_bin', eb='eb2')
ctoa_invalid = ddply(ss_corr[ss_corr$CueValid=='Invalid',], .(expt, targ_bin, Cond, subj), 
                     summarise, RT=median(RT))
# plot_box_ctoa(ctoa_invalid, 'RT Invalid (ms)', 'RT on Invalid Trials', out, 'targ_soa', eb='eb3')
ctoa_adv = merge(ctoa_valid, ctoa_invalid, by=c('expt', 'targ_bin', 'Cond', 'subj'))
ctoa_adv$RT = ctoa_adv$RT.y - ctoa_adv$RT.x  # Invalid - Valid RT
head(ctoa_adv)
# plot_box_ctoa(ctoa_adv, 'RT Invalid - Valid (ms)', 'RT Cueing Advantage', out, 'targ_soa', eb='eb3')
```


## Plotting the cueing advantage
```{r, fig.width=8.5, fig.height=4.5, results="hide"}
ctoa_adv$targ_bin = factor(ctoa_adv$targ_bin,
                           c('Early Target','Middle Target','Late Target')) #this works for lm
ctoa_adv$Cond = factor(ctoa_adv$Cond,
                           c('NoBlink','Artificial','Prompted')) #this works for lm
p = ggplot(data=ctoa_adv, aes(x=targ_bin, y=RT, fill=Cond)) + 
    geom_boxplot() + facet_grid(.~expt) + xlab('Target CTOA') + 
    ylab('RT (ms)') + theme_bw() + ylim(-180, 180) +
    # geom_dotplot(binaxis='y', stackdir='center', dotsize=2, binwidth=3, ) + 
    theme(panel.grid.minor=element_blank(), 
          plot.title = element_text(hjust = 0.5)) + ggtitle('Experiments 2 & 3 Comparison')
p = plot_themefy(p)
plot(p)
pdf('eb_expts2-3_adv.pdf', width=7.5, height=4.5)
plot(p)
dev.off()
```