---
title: '[eb4] Analyses'
author: "Egor Ananyev"
date: '2020-10-22'
output:
  html_document: 
    df_print: kable
    number_sections: yes
    toc: yes
    toc_depth: 4
    toc_float: yes
editor_options:
  chunk_output_type: inline
---

<style type="text/css">
body, td{
  font-family: Cambria;
}
code.r{
  font-family: Inconsolata;
}
</style>

# Data input and parsing
```{r set-options, message=F}
options(width=100)
out=F
library(plyr)
library(dplyr)
library(ggplot2)
library(lme4)
library(lmerTest)
library(reshape)
library(R.utils)
computer = 'acer'  # 'shocky', 'station3', 'acer' are all possible options
if(computer=='acer'){
  cloud_dir = 'C:/gd/'
  prog_dir = 'C:/Users/egora/Prog/'
}
if(computer=='shocky'){
  cloud_dir = 'C:/gd/'
  prog_dir = 'C:/Users/Egor/Prog/'
}
if(computer=='station3'){
  cloud_dir = '/home/station3/Desktop/Egor/'
  prog_dir = cloud_dir
}
if(computer == 'toshi') {
  cloud_dir = 'C:/Users/Egor/Google Drive/'
  prog_dir = 'C:/Users/Egor/'
}
sourceDirectory(paste0(prog_dir, 'eb/an/funs_an'))
source(paste0(cloud_dir, 'Prog/R/myFunctions/pvalfn.R'))
ds = read.csv(paste0(prog_dir, 'eb/an/consolidated/ds4.csv'))
dsa = read.csv(paste0(prog_dir, 'eb/an/consolidated/dsa4.csv'))
# Reordering levels of Condition variable, such that No Blink condition is the reference:
ds$Cond = factor(ds$Cond, c('NoBlink','Artificial','Prompted'))
ds$CondFull = factor(ds$CondFull, c('No Blink','Artificial Blink','Prompted Blink'))
cue_valid_name = 'Cue Validity'
```


# Cueing


## Boxplots
```{r, fig.width=8.5, fig.height=2.5, results="hide"}
ss_corr = ds[ds$corr_resp==1, ]
ctoa_valid = ddply(ss_corr[ss_corr$CueValid=='Valid',], .(targ_soa, Cond, subj), summarise,
                   RT=median(RT))
plot_box_ctoa(ctoa_valid, 'RT Valid (ms)', 'RT on Valid Trials', out, 'targ_soa', eb='eb3')
```

```{r, fig.width=8.5, fig.height=2.5, results="hide"}
ctoa_invalid = ddply(ss_corr[ss_corr$CueValid=='Invalid',], .(targ_soa, Cond, subj), summarise, 
                  RT=median(RT))
plot_box_ctoa(ctoa_invalid, 'RT Invalid (ms)', 'RT on Invalid Trials', out, 'targ_soa', eb='eb3')
```

```{r, fig.width=8.5, fig.height=2.5, results="hide"}
ctoa_adv = merge(ctoa_valid, ctoa_invalid, by=c('targ_soa', 'Cond', 'subj'))
ctoa_adv$RT = ctoa_adv$RT.y - ctoa_adv$RT.x  # Invalid - Valid RT
plot_box_ctoa(ctoa_adv, 'RT Invalid - Valid (ms)', 'RT Cueing Advantage', out, 'targ_soa', eb='eb3')
```

## Analyses

```{r}
print(lmerfn(lmer(RT ~ cue_valid * Cond * targ_soa + (1|subj), data = ss_corr)))
```

```{r}
print(anova(lmer(RT ~ cue_valid * Cond * targ_soa + (1|subj), data = ss_corr)))
```

# Eye blinks


## Blink durations

```{r}
dsa$bdur = dsa$tot_blank_time
bdur_sumss = ddply(dsa, .(Cond, subj), summarize, 
                        bdur_ave = mean(bdur),
                        bdur_sd = sd(bdur))
dsa = merge(dsa, bdur_sumss, by=c('Cond', 'subj'))
dsa$bdur_z = with(dsa, (bdur - bdur_ave) / bdur_sd)
```

```{r, fig.width=5.5, fig.height=2.5}
p = ggplot(dsa, aes(x=bdur, y=RT, color=CueValid)) + 
    stat_smooth(method='lm', alpha=0.15) +
    facet_grid(Cond~targ_soa) + guides(color=guide_legend(title='Cue Validity')) +
    xlab('Blink Duration (s)') + ylab('Reaction Time (ms)')
p = plot_themefy(p)
plot(p)
```

```{r}
print(lmerfn(lmer(RT ~ cue_valid * Cond * targ_soa * bdur + block + (1|subj), data = dsa)))
```


## Blink latencies

```{r}
dsa$blat = dsa$blank_time_beg - (dsa$cue_time - dsa$trial_time_beg)
blat_sumss = ddply(dsa, .(Cond, subj), summarize, 
                        blat_ave = mean(blat),
                        blat_sd = sd(blat))
dsa = merge(dsa, blat_sumss, by=c('Cond', 'subj'))
dsa$blat_z = with(dsa, (blat - blat_ave) / blat_sd)
```

```{r, fig.width=5.5, fig.height=2.5}
p = ggplot(dsa, aes(x=blat, y=RT, color=CueValid)) + 
    stat_smooth(method='lm', alpha=0.15) +
    facet_grid(Cond~targ_soa) + guides(color=guide_legend(title='Cue Validity')) +
    xlab('Blink Latency (s)') + ylab('Reaction Time (ms)')
p = plot_themefy(p)
plot(p)
```

```{r}
m = lmer(RT ~ cue_valid * Cond * targ_soa * blat + block + (1|subj), data = dsa)
print(lmerfn(m))
```

```{r}
print(anova(m))
```
