---
title: "Eye Blink Analysis"
author: "Egor Ananyev"
date: "December 5, 2018"
output:
    html_document:
        toc: true
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
body, td{
  font-family: Cambria;
}
code.r{
  font-family: Inconsolata;
}
</style>

# Data input and parsing
```{r set-options, message=F}
options(width=100)
dropbox_dir = '/Users/Egor/Dropbox/' # Mac / Toshi
# dropbox_dir = '/Users/egora/Dropbox/' # Shocky
data_dir = paste0(dropbox_dir, 'Projects/eb/data')
all_data_dirs = list.dirs(data_dir)[-1]  # excluding the first (base) directory
# TEMP: for now, just taking the last directory:
this_data_dir = all_data_dirs[length(all_data_dirs)]
file_name = dir(paste0(this_data_dir), pattern='.asc')
file_path = paste(this_data_dir, file_name, sep='/')

```

```{r}
# Read in the data:
raw_data = readLines(file_path)

# This function converts a specific chunk of raw data into a numeric data frame.
dfy = function(df_in, cols){
    ## The 'max_col' parameter identifies the number of columns to capture
    # First, we split the dataset by the tab '\t' delimeter:
    df_out = do.call(rbind, strsplit(df_in, '\t'))[,cols]
    # We then convert the resulting character matrix into a numeric data frame:
    if(is.null(dim(df_out))){  # if there is only a single dimension (i.e., a list), no need for 'apply'
        df_out = as.numeric(df_out)
    }else{  # otherwise, 'apply'ing 'as.numeric' conversion to columns:
        # To avoid the 'conversion to NA' warning, preassigning blink-related blank cells to NAs:
        df_out[df_out=='   .'] = NA
        df_out = data.frame(apply(df_out, 2, as.numeric))
    }
}
```

## Samples
```{r}
# extracting lines that start with numbers:
samples = raw_data[grepl('^[0-9]', raw_data)]
# creating a proper data frame:
df_samples = dfy(samples, 1:7)  # we only need 7 cols
colnames(df_samples) = c('time', 'xl', 'yl', 'psl', 'xr', 'yr', 'psr')
print(head(df_samples))
```

## Trial times
```{r}
# Storing the start and end trials times for later labeling
df_trials = data.frame(start=dfy(raw_data[grepl('^START', raw_data)], 2),
                       end=dfy(raw_data[grepl('^END', raw_data)], 2))
print(df_trials)
# Labeling trials in the 'samples' data frame
for(cur_trial in 1:nrow(df_trials)){
    df_samples$trial[df_samples$time >= df_trials$start[cur_trial]] = cur_trial
}
```

## Blink events
```{r}
# Extracting the lines with blink ends, as they include blink start, end, and duration:
blinks = raw_data[grepl('^EBLINK', raw_data)]
df_blinks = data.frame(do.call(rbind, strsplit(blinks, "\t", fixed=TRUE)))
df_blinks = cbind(df_blinks,
                  data.frame(do.call(rbind, strsplit(as.character(df_blinks[,1]), " ",
                                                     fixed=TRUE))))
df_blinks = df_blinks[,c(5,6,2,3)]
colnames(df_blinks) = c('eye', 'start', 'end', 'dur')
df_blinks[,2:4] = data.frame(apply(df_blinks[,2:4], 2, as.numeric))
print(head(df_blinks))
# TODO: the blink durations tend to be overestimated by 2 units
```

# Visualization for QC
```{r}
library(ggplot2)
# For simplicity, only visualizing the right eye at the moment:
ggplot(df_samples[df_samples$trial==4,], aes(x=time, y=yr)) + geom_line()
for(cur_trial in 1:nrow(df_trials)){
    p = ggplot(df_samples[df_samples$trial==cur_trial,], aes(x=time, y=yr)) + 
        geom_line() + ylim(350, 600) + geom_rect(data=df_blinks, inherit.aes=F, 
                                                 aes(xmin=start, xmax=end, ymin=350, ymax=600),
                                                 color='transparent', fill='red', alpha=.3)
    print(p)
}
```
