---
title: "[eb1] Quality Control"
author: "Egor Ananyev"
date: "2019-01-04"
output:
    html_document:
        toc: true
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
body, td{
  font-family: Cambria;
}
code.r{
  font-family: Inconsolata;
}
</style>

# Data input and parsing
```{r set-options, message=F}
# options(width=100)
eb = '2'
subj = 'subj-25'
cond = 'cond-v'
cue = 'cp'  # cp/cu = predictive/unpredictive
block = 4
debug = F
included_trials = c(1)  # if debug==T
# Exclusions constants:
eo_tolerance = 0.1  # 'eyes open' tolerance: time allowed to open eyes post target presentation
# Handling directories:
computer = 'acer'  # 'shocky', 'station3', 'acer' are all possible options
# if(computer=='shocky'){ cloud_dir='/Users/Egor/Dropbox/' }
# if(computer=='acer' || computer == 'toshi'){ cloud_dir = 'C:/Users/egora/Dropbox/' }
if(computer=='shocky' || computer=='acer'){
  cloud_dir = 'C:/gd/'
  prog_dir = 'C:/Users/egora/'
}
if(computer=='station3'){ cloud_dir = '/home/station3/Desktop/Egor/Dropbox/' }
library(R.utils)
library(plyr)
# sourceDirectory(paste0(cloud_dir, 'Projects/eb/eb/an/funs_qc'))
sourceDirectory(paste0(prog_dir, 'Prog/eb/an/funs_qc'))
# Getting the data directory:
data_dir = get_dir(cloud_dir, eb, cue, subj, cond, block)
# Reading raw data:
raw_data = read_em(data_dir)
# Parsing samples:
samples = parse_samples(raw_data)
samples$yr[is.na(samples$yr)] = 0
samples$xr = (samples$xr - (1152/2))/33.87  # normalizing to 0 and converting to dva
samples$yr = (samples$yr - (864/2))/33.87  # normalizing to 0 and converting to dva
# Parsing once-per-trial events
trials = parse_trials(raw_data, cond)
# Labeling trials in the 'samples' data frame with trial numbers & associating samples w/ time
samples = lab_samples(samples, trials)
# Parsing blank events (may be more than one per trial)
blanks = parse_blanks(raw_data, trials)
# Labeling samples with saccades:
samples = label_sacc_samples(samples, blanks, trials, sacc_thresh=2, eb_buff=50)
# Quantifying saccades for every trial:
sacc = quant_sacc(samples, trials)
# For debugging, picking a select few trials:
if(debug){
  samples = samples[samples$trial %in% included_trials,]
  trials = trials[trials$trial %in% included_trials,]
  blanks = blanks[blanks$trial %in% included_trials,]
  sacc = sacc[sacc$trial %in% included_trials,]
}
```

```{r}
# Including saccade summary in <trials>:
sacc_sum = ddply(sacc, .(trial), summarise,
                 sacc_num = length(trial),
                 sacc_R = sum(sacc_dir_R),
                 sacc_bef_targ = sum(bef_targ))
if(nrow(sacc_sum) > 0){
  trials = merge(trials, sacc_sum, by='trial', all=T)
} else {  # if there are no trials with saccades, assigning NA values to saccade columns
  trials$sacc_num = NA
  trials$sacc_R = NA
  trials$sacc_bef_targ = NA
}
# Including hori eye mvmt summary in <trials>:
xr_sum = ddply(samples, .(trial), summarise,
               xr_pre_cue_ave = mean(pre_cue, na.rm = T),
               xr_pre_eb_ave = mean(pre_eb, na.rm = T),
               xr_post_eb_ave = mean(post_eb, na.rm = T),
               xr_pre_targ_ave = mean(pre_targ, na.rm = T),
               xr_post_targ_ave = mean(post_targ, na.rm = T),
               xr_post_resp_ave = mean(post_resp, na.rm = T) )
trials = merge(trials, xr_sum, by='trial', all=T)
```

# Merging blanks & trials
```{r}
## TEMP:
# The merged data frame has trials and blanks combined:
merged = merge(trials, blanks, by='trial', all.x=T)
if(cond != 'cond-m'){
    # Reaction time is the response time stamp minus trial start time stamp:
    merged$rt = with(merged, resp_time - trial_time_beg)
}
merged$nonart = 1  # all blanks are considered non-artificial at first, which is overwritten in
# ... cond-a
```

# Automatic trial exclusion
```{r}
# In conditions that require blinking after the cue (voluntary and measurement):
# Excluding trials with no blink:
if(cond %in% c('cond-v', 'cond-m', 'cond-a')){
    cue_targ_blinks = with(merged, blank_time_beg > (cue_time-trial_time_beg+0.1) & 
                                   blank_time_end < (targ_time - trial_time_beg))
    # cue_targ_blinks = merged$blank_time_beg > (merged$cue_time - merged$trial_time_beg) &
    #                   merged$blank_time_end < (merged$targ_time - merged$trial_time_beg)
    excl_no_blink_trials = !merged$trial %in% merged$trial[cue_targ_blinks]
    if(sum(excl_no_blink_trials, na.rm=T)){  # if there is one or more such trials
        excl_no_blink = data.frame(trial = unique(merged$trial[excl_no_blink_trials]),
                                   excl_reason = 'no blink')
    # Important to account for situations when no blink has occurred on a given trial:
    excl_no_blink = excl_no_blink[!is.na(excl_no_blink$trial),]
    } else {
        excl_no_blink = NULL
    }
} else {
    excl_no_blink = NULL
}

# In control condition (that requires the subject not to blink)...
# Excluding trials with blinks between the cue and the target (prohibited blinks):
if(cond == 'cond-c' | cond == 'cond-a'){
    if(cond == 'cond-a'){
        # Blinks are prohibited during the 'artificial' blink condition, which is why they need to
        # ... be distinguished from the simulated ones:
        merged$nonart = 0
        # Pupil-detection or lost signal lags behind the shutter glasses by 1-5 samples:
        artif_inds = with(merged, blank_sample_beg >= cue_resp_sample &
                                  tot_blank_samples <= (shutter_sample_beg-shutter_sample_end)+10)
        # ... allowing some wiggle-time (ten samples) for pupil to be detected post-artblink
        merged$nonart[!artif_inds] = 1  # marking blanks that are not artificial blinks
    }
    excl_prohib_blink_trials = with(merged, blank_time_end > (cue_time - trial_time_beg) &
                                    blank_time_end < (targ_time - trial_time_beg) & nonart)
    if(sum(excl_prohib_blink_trials > 0, na.rm = T)){
      excl_prohib_blink = data.frame(trial = unique(merged$trial[excl_prohib_blink_trials]),
                                     excl_reason = 'prohibited blink')
      # Important to account for situations when no blink has occurred on a given trial:
      excl_prohib_blink = excl_prohib_blink[!is.na(excl_prohib_blink$trial),]
    } else {
      excl_prohib_blink = NULL
    }
} else {
    excl_prohib_blink = NULL
}

# Excluding trials with no space bar press in no-blink and AB conditions:
if((cond == 'cond-c' | cond == 'cond-a') & eb == '3'){
  if(sum(is.na(trials$cue_resp_time))){
    excl_nospace = data.frame(trial=trials$trial[is.na(trials$cue_resp_time)],
                                     excl_reason = 'no space press')
  } else {
    excl_nospace = NULL
  }
} else {
  excl_nospace = NULL
}

# In all experimental (non-measurement) conditions:
# Excluding trials with 'target blinks' (blinks during target presentation):
if(cond!='cond-m' & !is.null(blanks)){
  excl_targ_blink_trials = merged$blank_time_end > (merged$targ_time -
                                                    merged$trial_time_beg +
                                                    eo_tolerance) &
                           merged$blank_time_end < (merged$resp_time - 
                                                    merged$trial_time_beg)
  if(sum(excl_targ_blink_trials, na.rm=T)){
    # Finding blanks that occur more than 'eyes open' tolerance post-target presentation.
    excl_targ_blink = data.frame(trial = unique(merged$trial[excl_targ_blink_trials]),
                                 excl_reason = 'target blink')
    # Important to account for situations when no blink has occurred on a given trial:
    excl_targ_blink = excl_targ_blink[!is.na(excl_targ_blink$trial),]
  } else {
    excl_targ_blink = NULL
  }
} else {
  excl_targ_blink = NULL
}

# In all experimental conditions (non-measurement):
# Excluding trials with pre-cue blinks:
if(sum(blanks$blank_post_cue==0, na.rm = T) > 0){
  excl_precue_blink = data.frame(trial = blanks$trial[blanks$blank_post_cue == 0],
                                 excl_reason = 'pre-cue blink')
} else {
  excl_precue_blink = NULL
}

# In all conditions (including measurement):
# Excluding trials with pre-target saccades:
if(sum(trials$sacc_bef_targ, na.rm = T)){
  excl_sacc = data.frame(trial=trials$trial[trials$sacc_bef_targ > 0 &
                                                   !is.na(trials$sacc_bef_targ)],
                         excl_reason = 'saccade')
} else {
  excl_sacc = NULL
}
```

# Manual trial excl/inclusions
```{r}
# Obtaining the manual override, if it exists
manual = get_manual(data_dir)
if(!is.null(manual)){
  # In addition to the auto-excluded trials, we need to also exclude the manually excluded ones:
  if(sum(manual$excl0incl1==0)){
    list_excl = manual[manual$excl0incl1==0,]
    excl_manual = data.frame(trial = list_excl$trial, excl_reason = list_excl$reason)
  } else {
    excl_manual = NULL
  }
  # Also accounting for manual overrides of the auto-exclusions:
  if(sum(manual$excl0incl1==1)){
    list_incl = manual[manual$excl0incl1==1,]
    incl_manual = data.frame(trial = list_incl$trial, incl_reason = list_incl$reason)
  } else {
    incl_manual = NULL
  }
} else {
  excl_manual = NULL
  incl_manual = NULL
}
```

# Output
```{r}
# Printing all exclusions (if any) to screen and exporting:
all_excl = rbind(excl_targ_blink, excl_prohib_blink, excl_no_blink, excl_precue_blink,
                 excl_sacc, excl_nospace)
# Also attaching manual exclusions, if any:
if(!is.null(excl_manual)){
  all_excl = rbind(all_excl, excl_manual)
}
# Manually overriding any auto-exclusions, if any:
if(!is.null(incl_manual)){
  print('Warning! Manual exclusion override code has not been tested!')
  all_excl = all_excl(!all_excl$trial %in% unique(incl_manual$trial))
}
# Writing exclusions to a file:
if(!is.null(all_excl)){
  ( all_excl = all_excl[order(all_excl$trial),] )
  if(!debug){
    write_exclusions(all_excl, data_dir)
  }
}

# Exporting all trials
if(!is.null(all_excl)){
  merged = merge(merged, all_excl, by='trial', all=T)
} else {
  merged$excl_reason = NA
}
if(!debug){
  write.table(merged, paste(data_dir, 'eye_tracking.csv', sep='/'), row.names=F, sep=',')
}
```

# Visualization for QC
```{r, fig.width=4.5, fig.height=2.5}
# if(cond == 'cond-m'){
#   xlims = c(0, 2.2)
# }else{
#   xlims = c(0, 3.1)
# }
# Taking every third row (sufficient sampling for visualization):
sub_samples = samples[c(T,F,F,F,F,F,F,F,F,F),]
# Cycling through trials to visualize
# cur_trial = 39  #temp
for(cur_trial in trials$trial){
  # start.time <- Sys.time() 
  plot_qc(trial_samples = sub_samples[sub_samples$trial==cur_trial,],
          trial_blanks = blanks[blanks$trial==cur_trial,],
          this_trial = trials[trials$trial==cur_trial,],
          trial_sacc = sacc[sacc$trial==cur_trial,])
  # end.time <- Sys.time()
  # (time.taken <- end.time - start.time)
}
```

```{r}
# Criteria for exclusion:
# - More / fewer than one blank per trial
# - Blank occuring before the beep or not completing within the trial

## To write a CSV file with trial to exclude, run the following command:
# write_exclusions(9)
## To estimate blink parameters based on the included trials:
if(cond == 'cond-m'){
  estimate_blinks(data_dir, !is.null(all_excl))
}
```