---
title: "[eb1] Measurement - Quality Control"
author: "Egor Ananyev"
date: "2019-01-04"
output:
    html_document:
        toc: true
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
body, td{
  font-family: Cambria;
}
code.r{
  font-family: Inconsolata;
}
</style>

# Data input and parsing
```{r set-options, message=F}
options(width=100)
subj = 'subj-00'
cond = 'cond-m'
shocky = T
if(shocky){dropbox_dir='/Users/egora/Dropbox/'} else{dropbox_dir='/Users/Egor/Dropbox/'}
library(R.utils)
sourceDirectory(paste(dropbox_dir, 'Projects/eb/eb/an/funs', sep='/'))
# Getting the data directory:
this_data_dir = get_dir(subj, cond, dropbox_dir)
# Reading raw data:
raw_data = read_em(this_data_dir)
# Parsing samples:
samples = parse_samples(raw_data)
# Parsing once-per-trial events
trials = parse_trials(raw_data)
# Labeling trials in the 'samples' data frame with trial numbers & associating samples w/ time
samples = lab_samples(samples, trials)
# Parsing blank events (may be more than one per trial)
blanks = parse_blanks(raw_data, trials)
```

# Visualization for QC
```{r, fig.width=4.5, fig.height=2.5}
xlims = c(0, 2.2)
for(cur_trial in 1:nrow(trials)){
    plot_qc(samples, trials, xlims)
}
```

```{r}
## To write a CSV file with trial to exclude, run the following command:
# write_exclusions(c(12))
```